import {useFonts} from 'expo-font'

/*
 * IMPORTANT: This is unused. Expo statically extracts these fonts.
 *
 * All used fonts MUST be configured here. Unused fonts can be commented out.
 *
 * This is used for both web fonts and native fonts.
 */
export function DO_NOT_USE() {
  return useFonts({
    'Inter-Regular': require('../../../assets/fonts/inter/Inter-Regular.otf'),
    'Inter-Italic': require('../../../assets/fonts/inter/Inter-Italic.otf'),
    'Inter-Medium': require('../../../assets/fonts/inter/Inter-Medium.otf'),
    'Inter-MediumItalic': require('../../../assets/fonts/inter/Inter-MediumItalic.otf'),
    'Inter-SemiBold': require('../../../assets/fonts/inter/Inter-SemiBold.otf'),
    'Inter-SemiBoldItalic': require('../../../assets/fonts/inter/Inter-SemiBoldItalic.otf'),
    'Inter-Bold': require('../../../assets/fonts/inter/Inter-Bold.otf'),
    'Inter-BoldItalic': require('../../../assets/fonts/inter/Inter-BoldItalic.otf'),
    'Roboto Flex': require('../../../assets/fonts/roboto-flex/Roboto-Flex.ttf'),
    'Roboto Flex 2xl': require('./assets/fonts/roboto-flex/RobotoFlex-2xl.ttf'),
    'Roboto Flex 2xl Bold': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-bold.ttf'),
    'Roboto Flex 2xl Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-bold-italic.ttf'),
    'Roboto Flex 2xl Medium': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-medium.ttf'),
    'Roboto Flex 2xl Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-medium-italic.ttf'),
    'Roboto Flex 2xl Normal': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-normal.ttf'),
    'Roboto Flex 2xl Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-normal-italic.ttf'),
    'Roboto Flex 2xl Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-semibold.ttf'),
    'Roboto Flex 2xl Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xl-semibold-italic.ttf'),
    'Roboto Flex 2xs': require('./assets/fonts/roboto-flex/RobotoFlex-2xs.ttf'),
    'Roboto Flex 2xs Bold': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-bold.ttf'),
    'Roboto Flex 2xs Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-bold-italic.ttf'),
    'Roboto Flex 2xs Medium': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-medium.ttf'),
    'Roboto Flex 2xs Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-medium-italic.ttf'),
    'Roboto Flex 2xs Normal': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-normal.ttf'),
    'Roboto Flex 2xs Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-normal-italic.ttf'),
    'Roboto Flex 2xs Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-semibold.ttf'),
    'Roboto Flex 2xs Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-2xs-semibold-italic.ttf'),
    'Roboto Flex 3xl': require('./assets/fonts/roboto-flex/RobotoFlex-3xl.ttf'),
    'Roboto Flex 3xl Bold': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-bold.ttf'),
    'Roboto Flex 3xl Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-bold-italic.ttf'),
    'Roboto Flex 3xl Medium': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-medium.ttf'),
    'Roboto Flex 3xl Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-medium-italic.ttf'),
    'Roboto Flex 3xl Normal': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-normal.ttf'),
    'Roboto Flex 3xl Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-normal-italic.ttf'),
    'Roboto Flex 3xl Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-semibold.ttf'),
    'Roboto Flex 3xl Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-3xl-semibold-italic.ttf'),
    'Roboto Flex 4xl': require('./assets/fonts/roboto-flex/RobotoFlex-4xl.ttf'),
    'Roboto Flex 4xl Bold': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-bold.ttf'),
    'Roboto Flex 4xl Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-bold-italic.ttf'),
    'Roboto Flex 4xl Medium': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-medium.ttf'),
    'Roboto Flex 4xl Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-medium-italic.ttf'),
    'Roboto Flex 4xl Normal': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-normal.ttf'),
    'Roboto Flex 4xl Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-normal-italic.ttf'),
    'Roboto Flex 4xl Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-semibold.ttf'),
    'Roboto Flex 4xl Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-4xl-semibold-italic.ttf'),
    'Roboto Flex 5xl': require('./assets/fonts/roboto-flex/RobotoFlex-5xl.ttf'),
    'Roboto Flex 5xl Bold': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-bold.ttf'),
    'Roboto Flex 5xl Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-bold-italic.ttf'),
    'Roboto Flex 5xl Medium': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-medium.ttf'),
    'Roboto Flex 5xl Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-medium-italic.ttf'),
    'Roboto Flex 5xl Normal': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-normal.ttf'),
    'Roboto Flex 5xl Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-normal-italic.ttf'),
    'Roboto Flex 5xl Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-semibold.ttf'),
    'Roboto Flex 5xl Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-5xl-semibold-italic.ttf'),
    'Roboto Flex lg': require('./assets/fonts/roboto-flex/RobotoFlex-lg.ttf'),
    'Roboto Flex lg Bold': require('./assets/fonts/roboto-flex/RobotoFlex-lg-bold.ttf'),
    'Roboto Flex lg Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-lg-bold-italic.ttf'),
    'Roboto Flex lg Medium': require('./assets/fonts/roboto-flex/RobotoFlex-lg-medium.ttf'),
    'Roboto Flex lg Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-lg-medium-italic.ttf'),
    'Roboto Flex lg Normal': require('./assets/fonts/roboto-flex/RobotoFlex-lg-normal.ttf'),
    'Roboto Flex lg Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-lg-normal-italic.ttf'),
    'Roboto Flex lg Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-lg-semibold.ttf'),
    'Roboto Flex lg Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-lg-semibold-italic.ttf'),
    'Roboto Flex md': require('./assets/fonts/roboto-flex/RobotoFlex-md.ttf'),
    'Roboto Flex md Bold': require('./assets/fonts/roboto-flex/RobotoFlex-md-bold.ttf'),
    'Roboto Flex md Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-md-bold-italic.ttf'),
    'Roboto Flex md Medium': require('./assets/fonts/roboto-flex/RobotoFlex-md-medium.ttf'),
    'Roboto Flex md Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-md-medium-italic.ttf'),
    'Roboto Flex md Normal': require('./assets/fonts/roboto-flex/RobotoFlex-md-normal.ttf'),
    'Roboto Flex md Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-md-normal-italic.ttf'),
    'Roboto Flex md Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-md-semibold.ttf'),
    'Roboto Flex md Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-md-semibold-italic.ttf'),
    'Roboto Flex sm': require('./assets/fonts/roboto-flex/RobotoFlex-sm.ttf'),
    'Roboto Flex sm Bold': require('./assets/fonts/roboto-flex/RobotoFlex-sm-bold.ttf'),
    'Roboto Flex sm Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-sm-bold-italic.ttf'),
    'Roboto Flex sm Medium': require('./assets/fonts/roboto-flex/RobotoFlex-sm-medium.ttf'),
    'Roboto Flex sm Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-sm-medium-italic.ttf'),
    'Roboto Flex sm Normal': require('./assets/fonts/roboto-flex/RobotoFlex-sm-normal.ttf'),
    'Roboto Flex sm Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-sm-normal-italic.ttf'),
    'Roboto Flex sm Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-sm-semibold.ttf'),
    'Roboto Flex sm Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-sm-semibold-italic.ttf'),
    'Roboto Flex xl': require('./assets/fonts/roboto-flex/RobotoFlex-xl.ttf'),
    'Roboto Flex xl Bold': require('./assets/fonts/roboto-flex/RobotoFlex-xl-bold.ttf'),
    'Roboto Flex xl Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xl-bold-italic.ttf'),
    'Roboto Flex xl Medium': require('./assets/fonts/roboto-flex/RobotoFlex-xl-medium.ttf'),
    'Roboto Flex xl Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xl-medium-italic.ttf'),
    'Roboto Flex xl Normal': require('./assets/fonts/roboto-flex/RobotoFlex-xl-normal.ttf'),
    'Roboto Flex xl Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xl-normal-italic.ttf'),
    'Roboto Flex xl Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-xl-semibold.ttf'),
    'Roboto Flex xl Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xl-semibold-italic.ttf'),
    'Roboto Flex xs': require('./assets/fonts/roboto-flex/RobotoFlex-xs.ttf'),
    'Roboto Flex xs Bold': require('./assets/fonts/roboto-flex/RobotoFlex-xs-bold.ttf'),
    'Roboto Flex xs Bold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xs-bold-italic.ttf'),
    'Roboto Flex xs Medium': require('./assets/fonts/roboto-flex/RobotoFlex-xs-medium.ttf'),
    'Roboto Flex xs Medium Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xs-medium-italic.ttf'),
    'Roboto Flex xs Normal': require('./assets/fonts/roboto-flex/RobotoFlex-xs-normal.ttf'),
    'Roboto Flex xs Normal Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xs-normal-italic.ttf'),
    'Roboto Flex xs Semibold': require('./assets/fonts/roboto-flex/RobotoFlex-xs-semibold.ttf'),
    'Roboto Flex xs Semibold Italic': require('./assets/fonts/roboto-flex/RobotoFlex-xs-semibold-italic.ttf'),
  })
}
